### PR TITLE
Add manual capture in the document scanner

### PR DESCRIPTION
**Pull request by jas823**
I've added a green button for manual capture and followed suggestion from your developer. Please see changes and adjust  accordingly when integrating. Hoping this feature could be added.

### CODE REVIEW

**Comment by JonasLaux** [comment]
Hey,
thank you very much for you contribution! 
To integrate this in our Plugin, we need a view more additional implementations. The button should be customizable (a flag in the config, that enables or disables the button). Also, it would be nice to configurate the Position and Color of the Button. Additionally, a configurable text for the button would be very helpful. And what is very important, that we have both implementations (Android and iOS), otherwise, our plugin would have a different state of features between the platforms.

**Comment by JonasLaux** [comment]
Hey, thank you again for your contribution. We we were out of office the last 2 weeks, sorry for not comming back to you. The PR looks good, though. I will try to implement the iOS part next week, i hope i can make some free time there.
Thanks!

**Comment by bvanleeuwen1995** [comment]
Hi Jonas,

Is there any update on this Pull Request? We would like to include this feature in our app.

**Comment by JonasLaux** [comment]
yes, it is included in our 3.27 Release, which is tomorrow.

**Comment by JonasLaux** [comment]
Yes, it's merged and i made some changes to it. Unfortunately, we have bigger issues in our iOS SDK, so this feature will be Android only atm. 
We will have a look at the bug and fix it ASAP.

**Pull request closed without merging**
